version: '3.7'

services:
  currency-exchange:
    image: vctrtello1/microservices-currency-conversion-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8000:8000"
    networks:
      - currency-network
    depends_on: 
      - naming-server    

  naming-server:
    image: vctrtello1/microservices-naming-server:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - currency-network
networks:
  currency-network: