apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1"},"creationTimestamp":"2021-07-30T15:50:51Z","generation":4,"labels":{"app":"currency-exchange"},"name":"currency-exchange","namespace":"default","resourceVersion":"260094","uid":"53a27e6b-9201-4b47-a80f-2b9d268e8588"},"spec":{"progressDeadlineSeconds":600,"replicas":3,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"currency-exchange"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"currency-exchange"}},"spec":{"containers":[{"image":"vctrtello1/microservices-currency-exchange-service:0.0.11-SNAPSHOT","imagePullPolicy":"IfNotPresent","name":"microservices-currency-exchange-service","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2021-07-30T15:50:51Z","lastUpdateTime":"2021-07-30T15:50:55Z","message":"ReplicaSet \"currency-exchange-747564467c\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"},{"lastTransitionTime":"2021-08-01T20:38:53Z","lastUpdateTime":"2021-08-01T20:38:53Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"}],"observedGeneration":4,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
  creationTimestamp: "2021-08-01T21:42:47Z"
  generation: 1
  labels:
    app: currency-exchange
  name: currency-exchange
  namespace: default
  resourceVersion: "263785"
  uid: bb3f53f6-9ee3-401a-a5bc-d60ab0591968
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: currency-exchange
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: currency-exchange
    spec:
      containers:
      - image: vctrtello1/microservices-currency-exchange-service:0.0.12-SNAPSHOT      
        imagePullPolicy: IfNotPresent
        name: microservices-currency-exchange-service
        envFrom:
          - configMapRef:
              name: currency-conversion
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2021-08-01T21:42:54Z"
    lastUpdateTime: "2021-08-01T21:42:54Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-08-01T21:42:47Z"
    lastUpdateTime: "2021-08-01T21:42:54Z"
    message: ReplicaSet "currency-exchange-747564467c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
